# frozen_string_literal: true

# Subjects
Subject.create(name: 'Topología Y Análisis Real', code: '1886', credits: 10)
Subject.create(name: 'Funciones De Variable Compleja', code: '1066', credits: 5)
Subject.create(name: 'Cálculo Dif. E Integral En Una Variable', code: '1061', credits: 13)
Subject.create(name: 'Cálculo Dif. E Integral En Varias Variables', code: '1062', credits: 13)
Subject.create(name: 'Cálculo Vectorial', code: '1063', credits: 10)
Subject.create(name: 'Geometría Y Álgebra Lineal 1', code: '1030', credits: 9)
Subject.create(name: 'Geometría Y Álgebra Lineal 2', code: '1031', credits: 9)
Subject.create(name: 'Combinatoria Analitica', code: '1012', credits: 8)
Subject.create(name: 'Teoría De Cod. Algeb. Para Corr. De Errores', code: '1065', credits: 7)
Subject.create(name: 'Int. A La Teoría De La Información', code: '1450', credits: 8)
Subject.create(name: 'Lógica', code: '1027', credits: 12)
Subject.create(name: 'Lógica Modalidad Al Revés', code: '1013', credits: 12)
Subject.create(name: 'Matemática Discreta 1', code: '1023', credits: 9)
Subject.create(name: 'Matemática Discreta 2', code: '1026', credits: 9)
Subject.create(name: 'Int. A Las Ecuaciones Diferenciales', code: '1064', credits: 10)
Subject.create(name: 'Probabilidad Y Estadística', code: '1025', credits: 10)
Subject.create(name: 'Teoría De Codigos Avanzado', code: '1011', credits: 6)
Subject.create(name: 'Física 1', code: '1151', credits: 10)
Subject.create(name: 'Física 2', code: '1152', credits: 10)
Subject.create(name: 'Física 3', code: '1153', credits: 10)
Subject.create(name: 'Int. A La Física Moderna', code: '1131', credits: 10)
Subject.create(name: 'Visión 3d', code: '1145', credits: 12)
Subject.create(name: 'Programación Funcional', code: '1354', credits: 10)
Subject.create(name: 'Didactica De Algorit.y Estruct.de Datos', code: '1353', credits: 7)
Subject.create(name: 'Complejidad Computacional', code: '1355', credits: 9)
Subject.create(name: 'Teoría De La Computacion', code: '1358', credits: 7)
Subject.create(name: 'Compresion De Datos Sin Perdida', code: '1352', credits: 10)
Subject.create(name: 'Computacion Grafica Avanzada', code: '1349', credits: 12)
Subject.create(name: 'Const.formal De Progr.en Teoría De Tipos', code: '1337', credits: 12)
Subject.create(name: 'Const.formal De Progr.en Teoría De Tipos', code: '1347', credits: 12)
Subject.create(name: 'Diseño De Compiladores', code: '1331', credits: 12)
Subject.create(name: 'Int. A La Computacion Grafica', code: '1316', credits: 10)
Subject.create(name: 'Int. A La Programación Funcional', code: '1328', credits: 7)
Subject.create(name: 'Int. A La Programación Generica', code: '1333', credits: 10)
Subject.create(name: 'Int. A La Programación Lógica', code: '1329', credits: 7)
Subject.create(name: 'Programación Funcional Avanzada', code: '1350', credits: 12)
Subject.create(name: 'Programación Lógica', code: '1340', credits: 10)
Subject.create(name: 'Programación 1', code: '1322', credits: 10)
Subject.create(name: 'Programación 2', code: '1321', credits: 12)
Subject.create(name: 'Programación 3', code: '1323', credits: 15)
Subject.create(name: 'Programación 4', code: '1324', credits: 15)
Subject.create(name: 'Tecnologías Interactivas Y Videojuegos', code: '1304', credits: 4)
Subject.create(name: 'Teoría De La Computacion', code: '1336', credits: 4)
Subject.create(name: 'Teoría De Lenguajes', code: '1325', credits: 12)
Subject.create(name: 'Verificación De Modelos', code: '1346', credits: 10)
Subject.create(name: 'Taller De Iniciacion A Los Sistemas Ciber-fisicos', code: '1888', credits: 4)
Subject.create(name: 'Sistemas Embebidos Para Tiempo Real', code: '1556', credits: 10)
Subject.create(name: 'Taller De Sistemas Ciber-fisicos', code: '1952', credits: 6)
Subject.create(name: 'Taller De Radio Definida Por Software', code: '1546', credits: 8)
Subject.create(name: 'Criptografia', code: '1545', credits: 10)
Subject.create(name: 'Análisis Y Diseño De Algorit.distrib.en Redes', code: '1440', credits: 8)
Subject.create(name: 'Arquitectura De Computadoras', code: '1443', credits: 12)
Subject.create(name: 'Aspectos Avanz. De Arq.de Computadoras', code: '1444', credits: 8)
Subject.create(name: 'Aspectos Avanz. De Redes De Computadoras', code: '1448', credits: 8)
Subject.create(name: 'Comput.de Pr.gral.en Unid.de Proc.graf.', code: '1447', credits: 7)
Subject.create(name: 'Computacion De Alta Performance', code: '1434', credits: 10)
Subject.create(name: 'Fundamentos De Seguridad Informática', code: '5916', credits: 12)
Subject.create(name: 'Int. A La Teoría De La Información', code: '1432', credits: 8)
Subject.create(name: 'Int. A Las Redes De Computadoras', code: '1433', credits: 15)
Subject.create(name: 'Int. A Las Redes De Computadores', code: '1406', credits: 15)
Subject.create(name: 'Redes De Computadoras', code: '1446', credits: 12)
Subject.create(name: 'Robótica Embebida', code: '1442', credits: 10)
Subject.create(name: 'Sistemas Distribuidos', code: '1414', credits: 15)
Subject.create(name: 'Sistemas Operativos', code: '1537', credits: 12)
Subject.create(name: 'Taller De Arquitectura De Computadoras', code: '1445', credits: 3)
Subject.create(name: 'Taller De Firmware', code: '1428', credits: 10)
Subject.create(name: 'Taller De Gpgpu', code: '1449', credits: 7)
Subject.create(name: 'Taller De Seguridad Informática', code: '1437', credits: 7)
Subject.create(name: 'Taller De Sistemas Operativos', code: '1542', credits: 10)
Subject.create(name: 'Ciencia De Datos Y Lenguaje Natural', code: '1880', credits: 10)
Subject.create(name: 'Modelos Estadisticos Para Clasif. Y Regresion', code: '1868', credits: 6)
Subject.create(name: 'Aprendizaje Automático', code: '1866', credits: 12)
Subject.create(name: 'Reconocimiento De Patrones', code: '5842', credits: 12)
Subject.create(name: 'Robótica Educativa', code: '1865', credits: 8)
Subject.create(name: 'Análisis Semantico De Lenguaje Natural', code: '1864', credits: 8)
Subject.create(name: 'Fundamentos De La Robótica Autonoma', code: '1857', credits: 7)
Subject.create(name: 'Butia: Robótica Educativa', code: '1849', credits: 8)
Subject.create(name: 'Gramaticas Formales Para El Leng.natural', code: '1835', credits: 10)
Subject.create(name: 'I.a. Y Robótica', code: '1829', credits: 10)
Subject.create(name: 'Int. Al Procesamiento De Leng. Natural', code: '1828', credits: 12)
Subject.create(name: 'Int. Al Reconocimiento De Patrones', code: '5831', credits: 8)
Subject.create(name: 'Métodos De Aprendizaje Automático', code: '1834', credits: 9)
Subject.create(name: 'Robótica Basada En Comportamientos', code: '1848', credits: 15)
Subject.create(name: 'Ingeniería De Ontologias', code: '2418', credits: 6)
Subject.create(name: 'Integracion De Datos', code: '1867', credits: 8)
Subject.create(
  name: 'Sistemas De Información Para El Análisis De Grandes Volumenes De Datos',
  code: '1781',
  credits: 10
)
Subject.create(name: 'Calidad De Datos E Información', code: '1802', credits: 6)
Subject.create(name: 'Bases De Datos No Relacionales', code: '1949', credits: 10)
Subject.create(name: 'Taller De Leng.y Tec.de La Web Semantica', code: '1947', credits: 10)
Subject.create(name: 'Int. Al Middleware', code: '1948', credits: 10)
Subject.create(name: 'Administración Y Seguridad De Sistemas', code: '1918', credits: 10)
Subject.create(name: 'Calidad De Datos', code: '1935', credits: 8)
Subject.create(name: 'Diseño Y Construccion De Data Warehouse', code: '1939', credits: 10)
Subject.create(name: 'Fundamentos De Bases De Datos', code: '1911', credits: 15)
Subject.create(name: 'Fundamentos De La Web Semantica', code: '1942', credits: 8)
Subject.create(name: 'Int. A Los Sist. De Infor. Geografica', code: '1926', credits: 10)
Subject.create(name: 'Int. Al Middleware', code: '1936', credits: 8)
Subject.create(name: 'Integracion De Datos', code: '1941', credits: 8)
Subject.create(name: 'Metadata En Sistemas De Información', code: '1932', credits: 13)
Subject.create(name: 'Recuperacion De Inf. Y Recomend. En La Web (wir)', code: '1938', credits: 10)
Subject.create(name: 'Sistemas De Información En Salud', code: '1937', credits: 10)
Subject.create(name: 'Tecnicas Avanzadas Para La Gest. De Sist. De Inf.', code: '1933', credits: 15)
Subject.create(name: 'Métodos Numéricos', code: 'CIM20', credits: 10)
Subject.create(name: 'Aplicaciones Del Álgebra Lineal', code: '1872', credits: 9)
Subject.create(name: 'Álgebra Lineal Numerica', code: '5914', credits: 9)
Subject.create(name: 'Métodos Montecarlo', code: '1057', credits: 8)
Subject.create(name: 'Métodos Numéricos', code: '1033', credits: 8)
Subject.create(name: 'Tecnicas De Descomposicion En Programación Matemática', code: '2398', credits: 4)
Subject.create(name: 'Reformulaciones Y Algoritmos Para Planificacion De La Produccion', code: '1877', credits: 10)
Subject.create(name: 'Fundamentos De Optimización', code: '1871', credits: 6)
Subject.create(name: 'Principios De Logística Humanitaria', code: '1639', credits: 10)
Subject.create(name: 'Optimización Continua Y Aplicaciones', code: '1640', credits: 10)
Subject.create(
  name: 'Herramientas P/el Diseño Y Análisis De Redes De Transp.urb De Pasajeros',
  code: '3207',
  credits: 8
)
Subject.create(name: 'Diseño Topológico De Redes', code: '1458', credits: 11)
Subject.create(name: 'Investigación De Oper.y Gest. De Riesgos', code: '1779', credits: 6)
Subject.create(name: 'Algoritmos Evolutivos', code: '1637', credits: 10)
Subject.create(name: 'Modelos Comb. De Confiabilidad En Redes', code: '1636', credits: 10)
Subject.create(name: 'Metaheurísticas Y Optimización Sobre Redes (mor)', code: '1635', credits: 11)
Subject.create(name: 'Teoria, Algorit. Y Aplic. De Gest. Logis', code: '1633', credits: 8)
Subject.create(name: 'Análisis De Datos En Redes Complejas', code: '1634', credits: 10)
Subject.create(name: 'Fundamentos De Programación Entera', code: '1631', credits: 8)
Subject.create(name: 'Int. A La Investigación De Operaciones', code: '1610', credits: 10)
Subject.create(name: 'Investigación De Oper.y Gest. De Riesgos', code: '1630', credits: 6)
Subject.create(name: 'Metaheurísticas Y Optimización Sobre Redes', code: '1613', credits: 10)
Subject.create(name: 'Modelado Y Optimización', code: '1624', credits: 6)
Subject.create(name: 'Optimización Bajo Incertidumbre', code: '1632', credits: 8)
Subject.create(name: 'Simulacion A Eventos Discretos', code: '1617', credits: 10)
Subject.create(name: 'Ingeniería De Software Basada En Evidencias', code: '2417', credits: 8)
Subject.create(name: 'Formulación Y Evaluación De Proyectos De Inversión', code: 'D84', credits: 8)
Subject.create(name: 'Gestión De Proyectos', code: 'A66', credits: 10)
Subject.create(name: 'Investigación Mediante Encuestas En Computacion', code: '1782', credits: 5)
Subject.create(name: 'Taller De Plan Y Seg De Proy De Software', code: '1778', credits: 4)
Subject.create(name: 'Profesion En Ingeniería De Software', code: '1777', credits: 6)
Subject.create(name: 'Ingeniería De Software Empirica', code: '1773', credits: 7)
Subject.create(name: 'Ingeniería De Software Basada En Evid.y Rev.sist.', code: '1772', credits: 7)
Subject.create(name: 'Taller De Ing.dirigida Por Modelos', code: '1770', credits: 8)
Subject.create(name: 'Arquitectura De Software', code: '1743', credits: 12)
Subject.create(name: 'Int. A La Ingeniería De Software', code: '1716', credits: 10)
Subject.create(name: 'Int. A La Interac. Persona Computadora', code: '1736', credits: 6)
Subject.create(name: 'Interaccion Persona Computadora', code: '1749', credits: 12)
Subject.create(name: 'Princ.y Fund.del Proc.pers.de Software', code: '1767', credits: 7)
Subject.create(name: 'Profesion En Ingeniería De Software', code: '1769', credits: 4)
Subject.create(name: 'Relaciones Personales En Ing. De Soft. Y Ger. De Proy.', code: '1758', credits: 10)
Subject.create(name: 'Taller De Interaccion Persona Computad.', code: '1768', credits: 8)
Subject.create(name: 'Taller De Verificación Del Software', code: '1742', credits: 8)
Subject.create(name: 'Taller De Mineria De Procesos De Negocio (tpm)', code: '1876', credits: 8)
Subject.create(name: 'Diseño Organizacional', code: 'A42', credits: 10)
Subject.create(name: 'Taller De Robótica Educativa', code: '1780', credits: 6)
Subject.create(name: 'Taller De Sistemas Empresariales', code: '1775', credits: 15)
Subject.create(name: 'Taller De Eval. De Tecn. De La Inf.', code: '1774', credits: 10)
Subject.create(name: 'Pasantia (computacion)', code: '1731', credits: 10)
Subject.create(name: 'Proyecto De Grado', code: '1730', credits: 30)
Subject.create(name: 'Proyecto De Ingeniería De Software', code: '1721', credits: 15)
Subject.create(name: 'Seminario De Ingeniería Biomedica', code: '5705', credits: 4)
Subject.create(name: 'Taller De Gest.y Tec.proc.negocio (tbpm)', code: '1766', credits: 10)
Subject.create(name: 'Taller De Programación', code: '1327', credits: 15)
Subject.create(name: 'Taller De Sist. De Inf.geograf.empresar.', code: '1759', credits: 8)
Subject.create(name: 'Taller De Sistemas De Información 1', code: '1751', credits: 10)
Subject.create(name: 'Taller De Sistemas De Información 3', code: '1740', credits: 8)
Subject.create(name: 'Taller De Sistemas De Información 4', code: '1741', credits: 15)
Subject.create(name: 'Taller Sistemas De Información 2', code: '1735', credits: 15)
Subject.create(name: 'Taller De Sist. De Inf. Geo. Empres.', code: '1776', credits: 10)
Subject.create(name: 'Gestión De Calidad', code: '1954', credits: 7)
Subject.create(name: 'Cambio Organizacional', code: 'A83', credits: 10)
Subject.create(name: 'Sociología De La Empresa Y Management', code: 'S42', credits: 10)
Subject.create(name: 'Prospectiva: Construyendo El Futuro', code: 'I87', credits: 10)
Subject.create(name: 'Planificación Estratégica', code: 'D85', credits: 4)
Subject.create(name: 'Introducción Al Emprendedurismo', code: 'A65', credits: 10)
Subject.create(name: 'Introducción A Los Sistemas De Gestión', code: '618EU', credits: 4)
Subject.create(name: 'Propiedad Intelectual', code: '559EU', credits: 3)
Subject.create(name: 'Int. Al Negocio Del Software', code: '1543', credits: 6)
Subject.create(name: 'Administración General Para Ingenieros', code: '1944', credits: 5)
Subject.create(name: 'Control De Calidad', code: '1510', credits: 8)
Subject.create(name: 'Gestión De Calidad', code: '1940', credits: 6)
Subject.create(name: 'Int. A La Administración Para Ingenieros', code: '1519', credits: 10)
Subject.create(name: 'Práctica De Administración Para Ingenieros', code: '1945', credits: 5)
Subject.create(name: 'Gestión De La Innovación Y La Tecnología', code: 'A62', credits: 10)
Subject.create(name: 'Ciudadania En Entornos Digitales', code: '1270', credits: 6)
Subject.create(name: 'Ciencia, Tecnología Y Sociedad', code: '1223', credits: 8)
Subject.create(name: 'Economía', code: '1224', credits: 7)
Subject.create(name: 'Políticas Cientificas En Inf.y Comp.', code: '1225', credits: 3)
Subject.create(name: 'Tratamiento De Imágenes Por Computadora', code: '5828', credits: 10)
Subject.create(name: 'Tutorías Entre Pares 2', code: '2217', credits: 4)
Subject.create(name: 'Taller Encarare: Crear', code: '1216', credits: 8)
Subject.create(name: 'Aplicacion De Teoría De La Inf.al Proc.de Imag.', code: '1438', credits: 6)
Subject.create(name: 'Imágenes Medicas: Adquisicion, Instrumentacion Y Gestión', code: '5707', credits: 8)
Subject.create(name: 'Imágenes Medicas:adq. Instrum. Y Gestión', code: '5709', credits: 6)
Subject.create(name: 'Planificacion De Clases: Diseño De Unid.didact.', code: '1213', credits: 2)
Subject.create(name: 'Taller Encarare 1:creatividad E Innovac.', code: '2034', credits: 5)
Subject.create(name: 'Taller Encarare 2:planif.de La Fut.empr.', code: '2036', credits: 5)
