production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>

staging:
  secret_key_base: "secret_key_base"

development:
  secret_key_base: "secret_key_base"

test:
  secret_key_base: "secret_key_base"

